/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module change_rtl(i_argA, o_result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input [3:0] i_argA;
  output [3:0] o_result;
  assign _00_ = i_argA[3] & i_argA[1];
  assign _01_ = i_argA[3] & i_argA[0];
  assign o_result[1] = i_argA[1] ^ _01_;
  assign _02_ = i_argA[3] & i_argA[2];
  assign _03_ = _00_ | _01_;
  assign o_result[2] = i_argA[2] ^ _03_;
  assign o_result[3] = _02_ | _03_;
  assign o_result[0] = i_argA[0];
endmodule
