/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module dodawanie_rtl(i_argA, i_argB, o_result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input [3:0] i_argA;
  input [3:0] i_argB;
  output [3:0] o_result;
  assign _00_ = i_argA[0] & i_argB[0];
  assign _01_ = i_argA[1] & i_argB[1];
  assign _02_ = i_argA[1] ^ i_argB[1];
  assign _03_ = _00_ & _02_;
  assign o_result[1] = _00_ ^ _02_;
  assign _04_ = _01_ | _03_;
  assign _05_ = i_argA[2] & i_argB[2];
  assign _06_ = i_argA[2] ^ i_argB[2];
  assign _07_ = _04_ & _06_;
  assign o_result[2] = _04_ ^ _06_;
  assign _08_ = _05_ | _07_;
  assign _09_ = i_argA[3] ^ i_argB[3];
  assign o_result[3] = _08_ ^ _09_;
  assign o_result[0] = i_argA[0] ^ i_argB[0];
endmodule
